Vagrant.configure(2) do |config|
	config.vm.box = "centos/7"
	config.vm.box_url = "centos/7"

	config.vm.provision "file", source: "./", destination: "/home/vagrant"
	config.vm.define "juricharS" do |control|
		control.vm.hostname = "juricharS"
		control.vm.network "private_network", ip: "192.168.56.110"
		control.vm.provider "virtualbox" do |v|
			v.customize [ "modifyvm", :id, "--cpus", "2" ]
			v.customize [ "modifyvm", :id, "--memory", "2048" ]
		end
		config.vm.provision "shell",
			inline: "chmod +x /vagrant/setup.sh && /vagrant/setup.sh",
			run: "always"
	end
end
