Vagrant.configure(2) do |config|
common = <<-SHELL
    sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
    sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
    sudo yum -y install vim tree net-tools telnet git python3
    sudo echo 'autocmd filetype yaml setlocal ai ts=2 sw=2 et' > /home/vagrant/.vimrc
    sudo echo 'alias python=/usr/bin/python3' >> /home/vagrant/.bashrc
    sudo echo 'alias k=kubectl' >> /home/vagrant/.bashrc
    sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config
    sudo systemctl restart sshd
SHELL
  	config.vm.box = 'centos/8'
  	config.vm.box_version = '2011.0'
  	config.vm.box_url = 'https://app.vagrantup.com/centos/boxes/8'

	config.vm.provision "file", source: "./", destination: "/home/vagrant"
	config.vm.define "juricharS" do |control|
		control.vm.hostname = "juricharS"
		control.vm.network "private_network", ip: "192.168.56.110"
		control.vm.provider "virtualbox" do |v|
			v.customize [ "modifyvm", :id, "--cpus", "2" ]
			v.customize [ "modifyvm", :id, "--memory", "2048" ]
		end
		config.vm.provision "shell",
			inline: "chmod +x /vagrant/setup.sh && /vagrant/setup.sh",
			run: "always"
	end
end
