  # -*- mode: ruby -*-
  # vi: set ft=ruby :

  # All Vagrant configuration is done below. The "2" in Vagrant.configure
  # configures the configuration version (we support older styles for
  # backwards compatibility). Please don't change it unless you know what
  # you're doing.
  Vagrant.configure("2") do |config|
    # The most common configuration options are documented and commented below.
    # For a complete reference, please see the online documentation at
    # https://docs.vagrantup.com.

    # Every Vagrant development environment requires a box. You can search for
    # boxes at https://vagrantcloud.com/search.
  
    config.vm.box = "centos/8"
    config.vm.box_version = "2011.0"
    config.vm.box_url = "https://app.vagrantup.com/centos/boxes/8"
    
    config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/me.pub"
    config.vm.provision "shell", inline: <<-SHELL
      cat /home/vagrant/.ssh/me.pub >> /home/vagrant/.ssh/authorized_keys
    SHELL

    config.vm.define "mpochardS" do |control|
      control.vm.provider "virtualbox" do |vb|
        vb.name = "mpochardS"
        vb.customize ["modifyvm", :id, "--cpuexecutioncap", "50", "--name", "mpochardS"]
        vb.linked_clone = true
        vb.check_guest_additions = false
        vb.memory = "1024"
        vb.cpus = "1"
      end      
      control.vm.hostname = "mpochardS"
      control.vm.network "private_network", ip: "192.168.56.110", auto_config: false
      control.vm.provision "shell", inline: "sudo ip route replace default via 192.168.56.110 dev eth1"
    end

    config.vm.define "mpochardSW" do |control|

      control.vm.provider "virtualbox" do |vb|
        vb.name = "mpochardSW"
        vb.customize ["modifyvm", :id, "--cpuexecutioncap", "50", "--name", "mpochardSW"]
        vb.linked_clone = true
        vb.check_guest_additions = false
        vb.memory = "1024"
        vb.cpus = "1"
      end

      control.vm.hostname = "mpochardSW"
      control.vm.network "private_network", ip: "192.168.56.111", hostname: true, auto_config: false
      control.vm.provision "shell", inline: "sudo ip route replace default via 192.168.56.111 dev eth1"
    end
  end
