# frozen_string_literal: true

# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  common = <<-SHELL
    sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
    sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
    sudo yum -y install vim tree net-tools telnet git python3
    sudo echo 'autocmd filetype yaml setlocal ai ts=2 sw=2 et' > /home/vagrant/.vimrc
    sudo echo 'alias python=/usr/bin/python3' >> /home/vagrant/.bashrc
    sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config
    sudo systemctl restart sshd
  SHELL

  config.vm.box = 'centos/8'
  config.vm.box_version = '2011.0'
  config.vm.box_url = 'https://app.vagrantup.com/centos/boxes/8'

  config.vm.define 'mpochardS' do |control|
    control.vm.hostname = 'mpochardS'
    control.vm.network 'private_network', ip: '192.168.42.110'
    control.vm.provider 'virtualbox' do |v|
      v.name = 'mpochardS'
      v.check_guest_additions = false
      v.memory = '1024'
      v.cpus = '1'
      v.customize ['modifyvm', :id, '--cpuexecutioncap', '50', '--name', 'mpochardS']
      v.customize ['modifyvm', :id, '--natdnshostresolver1', 'on']
      v.customize ['modifyvm', :id, '--natdnsproxy1', 'on']
    end
    control.vm.provision :shell, inline: common
    control.vm.provision 'shell', inline: <<-SHELL
    curl -sfL https://get.k3s.io |
      INSTALL_K3S_VERSION=v1.19.2+k3s1 \
      K3S_KUBECONFIG_MODE='644' \
      INSTALL_K3S_EXEC='--flannel-iface 'eth1'' \
      sh -
      echo '$(cat /var/lib/rancher/k3s/server/node-token)' > /vagrant/k3s_token
    SHELL
  end

  config.vm.define 'mpochardSW' do |control|
    control.vm.hostname = 'mpochardSW'
    control.vm.network 'private_network', ip: '192.168.42.111'
    control.vm.provider 'virtualbox' do |v|
      v.name = 'mpochardSW'
      v.check_guest_additions = false
      v.memory = '1024'
      v.cpus = '1'
      v.customize ['modifyvm', :id, '--cpuexecutioncap', '50', '--name', 'mpochardSW']
      v.customize ['modifyvm', :id, '--natdnshostresolver1', 'on']
      v.customize ['modifyvm', :id, '--natdnsproxy1', 'on']
    end
    control.vm.provision :shell, inline: common
    control.vm.provision :shell, inline: <<-SHELL
      export K3S_TOKEN=$(cat /vagrant/k3s_token)
      curl -sfL https://get.k3s.io |
        INSTALL_K3S_EXEC='--flannel-iface 'eth1''\
        INSTALL_K3S_VERSION=v1.19.2+k3s1 \
        K3S_URL=https://192.168.42.110:6443 \
        K3S_TOKEN=$K3S_TOKEN \
        K3S_KUBECONFIG_MODE='644' \
        sh -
      echo 'LE TOKEN DU SERVEUR EST: $K3S_TOKEN'
    SHELL
  end
end
