apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: part3
spec:
  project: default

  source:
    repoURL: https://github.com/m3L4n/mpochard-config.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: false
