apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: wil-playground-project
  labels:
    app: wil-playground
spec:
  # Project description
  description: Our ArgoCD Project to deploy our app locally
  # Allow manifests to deploy only from our git repositories
  sourceRepos:
  - "https://github.com/m3L4n/*"
  # Only permit to deploy applications in the same cluster
  destinations:
  - namespace: dev
    server: https://kubernetes.default.svc
  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: false
